[package]
name = "particle"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
rayon = "1.10.0"
itertools = "0.14.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
